# pyproject.toml

[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "benderslib"
version = "0.5.1"
description = "A Benders Decomposition Library in Python"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Peng-Hui Guo", email = "m@guo.ph" },
]
requires-python = ">=3.10"  # BendersLib was developed with Python 3.12
keywords = ["benders decomposition", "optimization", "mathematical programming", "operations research"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.0.0",
]

[project.urls]
Homepage = "https://benders.dev"
Repository = "https://github.com/phguo/benderslib"

[tool.setuptools.packages.find]
where = ["."]
include = ["benderslib*"]
exclude = ["docs*", "examples*", "tests*"]

[tool.setuptools]
package-data = { "benderslib" = [] }

[tool.coverage.run]
source = ["benderslib"]

[project.optional-dependencies]
plot = ["matplotlib>=3.10.5"]
doc = [
    "sphinx>=8.2.3",
    "furo>=2025.9.25",
    "sphinx-copybutton>=0.5.2",
    "sphinx-gallery>=0.19.0",
    "sphinxcontrib-mermaid>=1.0.0",
    "sphinx_inline_tabs>=2025.12.21.14",
    "sphinx-tags>=0.4.0",
    "sphinx_contributors>=0.2.7",
    "sphinx-sitemap>=2.9.0",
    "benderslib[plot]",
]
copt = ["coptpy>=8.0.2; python_version<='3.13'"]
cplex = ["cplex>=22.1.2"]
cplexcp = ["docplex>=2.31.254"]
gurobi = ["gurobipy[matrixapi]>=12.0.0"]
ortools = ["ortools>=9.15.6755"]
pyomo = ["pyomo>=6.9.5"]
scip = ["pyscipopt>=6.0.0"]
all-solvers = ["benderslib[copt,cplex,cplexcp,gurobi,ortools,pyomo,scip]"]
test = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "tox>=3.28.0",
]
dev = [
    "benderslib[test,doc,all-solvers]",
    "build",
    "twine",
]
